name: Deploy to WordPress.org
on:
  push:
    tags:
      - '*'
jobs:
  tag:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: WordPress Plugin Deploy
        uses: everpress-co/action-wordpress-plugin-deploy@main
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
